# Generated by Django 3.0.8 on 2021-07-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.CharField(max_length=100)),
                ('product_img', models.ImageField(default='', upload_to='static/images')),
            ],
        ),
    ]
