# Generated by Django 3.0.8 on 2021-07-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_img',
        ),
    ]
