# Generated by Django 3.0.8 on 2021-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0005_auto_20210716_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productl_image', models.ImageField(default='', upload_to='ssproject/images')),
                ('productl_name', models.CharField(max_length=20)),
                ('productl_price', models.IntegerField()),
                ('productl_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productst_image', models.ImageField(default='', upload_to='ssproject/images')),
                ('productst_name', models.CharField(max_length=20)),
                ('productst_price', models.IntegerField()),
                ('productst_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttab_image', models.ImageField(default='', upload_to='ssproject/images')),
                ('producttab_name', models.CharField(max_length=20)),
                ('producttab_price', models.IntegerField()),
                ('producttab_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_uniform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productu_image', models.ImageField(default='', upload_to='ssproject/images')),
                ('productu_name', models.CharField(max_length=20)),
                ('productu_price', models.IntegerField()),
                ('productu_desc', models.CharField(max_length=100)),
            ],
        ),
    ]
