# Generated by Django 3.0.8 on 2021-07-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0006_product_laptop_product_stationery_product_tablet_product_uniform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.CharField(max_length=50)),
                ('cart_itemdesc', models.CharField(max_length=100)),
                ('cart_price', models.IntegerField(max_length=50)),
            ],
        ),
    ]
