# Generated by Django 3.0.8 on 2021-07-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_itemdesc',
            field=models.CharField(max_length=100, null='true'),
        ),
    ]
