# Generated by Django 3.0.8 on 2021-07-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0008_auto_20210720_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_item',
            field=models.CharField(max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.IntegerField(max_length=50, null='true'),
        ),
    ]
