# Generated by Django 3.0.8 on 2021-07-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0009_auto_20210720_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_itemdesc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(null=True, to='stdstrproject.Product'),
        ),
    ]
