# Generated by Django 3.0.8 on 2021-07-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0010_auto_20210721_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_uniform',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stdstrproject.Product'),
        ),
    ]
