# Generated by Django 3.0.8 on 2021-07-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0011_product_uniform_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_uniform',
            name='product_name',
        ),
    ]
