# Generated by Django 3.0.8 on 2021-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0012_remove_product_uniform_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(null=True, to='stdstrproject.Product_uniform'),
        ),
    ]
