# Generated by Django 3.0.8 on 2021-07-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0013_auto_20210722_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_item',
            new_name='productu_name',
        ),
    ]
