# Generated by Django 2.2.14 on 2021-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstrproject', '0014_auto_20210722_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_name', models.CharField(max_length=50)),
                ('pdf_file', models.FileField(default='', upload_to='ssproject/pdf')),
            ],
        ),
    ]
